---
- name: create users 
  hosts: "masters, workers"
  remote_user: tatek_soli # needs to be adjusted 
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  import_tasks : users.yml
    
