---
    - name: Create Ingress
      become: true
      become_user: kube
      become_method: sudo
      shell: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.5.1/deploy/crds.yaml
      args:
        chdir: $HOME